replicaCount: 2

image:
  repository: tejasbhosale008/helloworld
  tag: 165857b
  pullPolicy: IfNotPresent
env:
  - name: LOG_LEVEL
    value: INFO
  - name: APP_ENV
    value: stag

resources:
  requests:
    cpu: 250m
    memory: 250Mi
  limits:
    cpu: 500m
    memory: 512Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 80 # Optional

